drop table if exists pasaporte cascade; 
drop table if exists usuario cascade;

create table pasaporte (
    fecha_caducidad date,
    id integer generated by default as identity,
    id_usuario integer unique,
    numero varchar(255),
    pais_expedicion varchar(255),
    primary key (id)
);

create table usuario (
    id integer generated by default as identity,
    nombre varchar(255),
    apellidos varchar(255),
    email varchar(255),
    telefono varchar(255),
    fecha_nacimiento date,
    primary key (id)
);
