-- Eliminar tablas en orden inverso de jerarquía
drop table if exists reserva cascade;
drop table if exists guia cascade;
drop table if exists pasaporte cascade; 
drop table if exists usuario cascade;
drop table if exists destino cascade;

-- TABLA DESTINO
create table destino (
    id integer generated by default as identity,
    ciudad varchar(255),
    pais varchar(255),
    precio double precision,
    requiere_pasaporte boolean,
    primary key (id)
);

-- TABLA USUARIO
create table usuario (
    id integer generated by default as identity,
    nombre varchar(255),
    apellidos varchar(255),
    email varchar(255),
    telefono varchar(255),
    fecha_nacimiento date,
    primary key (id)
);

-- TABLA PASAPORTE
create table pasaporte (
    id integer generated by default as identity,
    numero varchar(255),
    pais_expedicion varchar(255),
    fecha_caducidad date,
    id_usuario integer unique,
    primary key (id),
    foreign key (id_usuario) references usuario(id) on delete cascade
);

-- TABLA GUIA
create table guia (
    id integer generated by default as identity,
    nombre varchar(255),
    apellidos varchar(255),
    especialidad varchar(255), -- Lo tratamos como varchar para el Enum de Java
    id_destino integer,
    primary key (id),
    foreign key (id_destino) references destino(id) on delete set null
);

-- TABLA RESERVA
create table reserva (
    id integer generated by default as identity,
    fecha date,
    id_usuario integer,
    id_destino integer,
    precio_total double precision,
    primary key (id),
    foreign key (id_usuario) references usuario(id) on delete cascade,
    foreign key (id_destino) references destino(id) on delete cascade
);